# Generated by Django 2.2.24 on 2022-11-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20221105_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint',
            new_name='text',
        ),
    ]
